### ISSUE TITLE
OS support

### ISSUE THREAD

**Issue by N4Z4** [TKCERT/winnti-nmap-script#2]
Hi,

i'm currently testing your script on 2 servers, ubuntu 16.04 and 18.04 server.
It's working on the 16.04 os but not on the 18.04.
 I've you alredy testing on other os servers ?   
Thank's a lot

**Comment by sruester** [comment]
Please provide more details (e.g. the actual error message).

N4Z4 <notifications@github.com> schrieb am Di., 28. Mai 2019, 11:42:

**Comment by N4Z4** [comment]
As you can see in the following logs :
On ubuntu 16.04 with :
Nmap version 7.60 ( https://nmap.org )
Platform: x86_64-unknown-linux-gnu
Compiled with: nmap-liblua-5.3.3 openssl-1.0.2g nmap-libssh2-1.8.0 libz-1.2.8 nmap-libpcre-7.6 nmap-libpcap-1.7.3 nmap-libdnet-1.12 ipv6
Compiled without:
Available nsock engines: epoll poll select

The script is working 
Starting Nmap 7.60 ( https://nmap.org ) at 2019-05-28 11:06 CEST
Nmap scan report for localhost (127.0.0.1)
Host is up (0.00066s latency).

PORT    STATE  SERVICE
80/tcp  closed http
631/tcp open   ipp

Host script results:
| winnti-detect: 
|   PORTS
|_      631 clean

Nmap done: 1 IP address (1 host up) scanned in 0.67 seconds

And on ubuntu 18.04 
Nmap version 7.60 ( https://nmap.org )
Platform: x86_64-unknown-linux-gnu
Compiled with: nmap-liblua-5.3.3 nmap-libz-1.2.8 nmap-libpcre-7.6 nmap-libpcap-1.7.3 nmap-libdnet-1.12 ipv6
Compiled without: openssl libssh2
Available nsock engines: epoll poll select

Nmap does not provide the winnti detect part :

Starting Nmap 7.60 ( https://nmap.org ) at 2019-05-28 09:06 UTC
Nmap scan report for localhost.localdomain (127.0.0.1)
Host is up (0.00016s latency).

PORT    STATE  SERVICE
80/tcp  closed http
631/tcp closed ipp

Nmap done: 1 IP address (1 host up) scanned in 0.39 seconds

Both script are execute in the same environnement.

**Comment by N4Z4** [comment]
Sorry, it's just the ipp service is not listening ^^
