### ISSUE TITLE
getting error on running the script

### ISSUE THREAD

**Issue by jameslee007** [TKCERT/winnti-nmap-script#4]
Hi There,

I am getting the below error when i run the nmap scan with the winnti-detect script.

Starting Nmap ( http://nmap.org ) at 2019-07-15 13:12 IST
NSE: failed to initialize the script engine:
/usr/bin/../share/nmap/nse_main.lua:235: /usr/bin/../share/nmap/scripts/winnti-detect.nse:268: ')' expected near '&'
stack traceback:
        [C]: in function 'assert'
        /usr/bin/../share/nmap/nse_main.lua:235: in function 'loadscript'
        /usr/bin/../share/nmap/nse_main.lua:534: in function 'new'
        /usr/bin/../share/nmap/nse_main.lua:788: in function 'get_chosen_scripts'
        /usr/bin/../share/nmap/nse_main.lua:1276: in main chunk
        [C]: in ?

QUITTING!

I am using centos - FYI

Please help me on this.

**Comment by ghost** [comment]
The readme says:
> This script needs liblua 5.3 to work. You may want to download the latest Nmap version to get support out of the box (confirmed working with Nmap 7.25BETA2 and 7.60).

centos has nmap 6.40

**Comment by mback2k** [comment]
The answer to this issue has already been given above.
